### ISSUE TITLE
Port, Benutzername und Passwort

### ISSUE THREAD

**Issue by wusa88** [etobi/bt2mqtt-scripts#2]
Hallo etobi,

ist es möglich, einen anderen Port zu verwenden?

Außerdem, ist es möglich einen Benutzername und ein Passwort einzugeben, welcher im Broker gesetzt wurde?

Danke

**Comment by etobi** [comment]
Hej,

in den Scripten vorgesehen ist das im Moment nicht, aber schau mal in der Datei `ibbq.sh` bzw. `xiaomi_mijia_ht.sh`

https://github.com/etobi/bt2mqtt-scripts/blob/master/bin/action/ibbq.sh#L13
https://github.com/etobi/bt2mqtt-scripts/blob/master/bin/action/xiaomi_mijia_ht.sh#L67

Dort wird `mosquitto_pub` benutzt um die MQTT-Nachricht zu verschicken. Dort kannst Du eigene Parameter erweitern, z.B. `[-p port] [-u username] [-P password]`

**Comment by etobi** [comment]
Ich benutze diese Skripte nicht mehr aktiv, daher werde ich keine Erweiterung der Skripte mehr machen - aber Du kannst das Repo natürlich gerne forken.
